# Generated by Django 2.2.2 on 2019-06-24 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('race', models.CharField(max_length=100)),
                ('orientation', models.CharField(max_length=100)),
                ('transplant', models.BooleanField(default=False)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('cohort', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup', models.BooleanField(default=False)),
                ('org_size', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('adies_present', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_amount', models.IntegerField()),
                ('signing_bonus', models.IntegerField()),
                ('negotiations', models.BooleanField(default=False)),
                ('relocation_package', models.BooleanField(default=False)),
                ('health_insurance', models.BooleanField(default=False)),
                ('retirement_matching', models.IntegerField()),
                ('vacation_days', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adieup.Adie')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adieup.Company')),
            ],
        ),
    ]
