# Generated by Django 2.2.2 on 2019-06-27 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adieup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adie',
            name='cohort',
        ),
    ]
